apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: mottak-dag-
spec:
  entrypoint: mottak
  templates:
  - name: mottak
    # Enable workflow logging to artifacts stored in objectstore (doesn't seem to work)
    archiveLocation:
      archiveLogs: true
    dag:
      tasks:
          # Todo - make the condition less verbose so we don't have to state every condition. dont know how.
        - name: task-kontroll
          template: sjekksum-kontroll
        - name: task-sjekksum-feil
          template: sjekksum-feil
          dependencies: [task-kontroll]
          when: "'{{tasks.task-kontroll.outputs.parameters.checksum_result}}' != 'ok'"
        - name: task-avscan
          template: avscan
          dependencies: [task-kontroll]
          when: "'{{tasks.task-kontroll.outputs.parameters.checksum_result}}' == 'ok'"
        - name: task-arkade5
          template: arkade5
          dependencies: [task-avscan]
          # Don't run arkade5 if the checksum was all wrong.
          when: "'{{tasks.task-kontroll.outputs.parameters.checksum_result}}' == 'ok'"
        - name: task-nytt-arkiv
          template: nytt-arkiv
          dependencies: [task-arkade5]
          when: "'{{tasks.task-kontroll.outputs.parameters.checksum_result}}' == 'ok'"

  - name: sjekksum-kontroll
    container: 
      image: gcr.io/mottak/s3-checksum256
      imagePullPolicy: Always
      env:
        - name: ENDPOINT
          value:  '{{workflow.parameters.ENDPOINT}}'
        - name: REGION_NAME
          value: 'us-east-1'
        - name: AWS_ACCESS_KEY_ID
          value: '{{workflow.parameters.AWS_ACCESS_KEY_ID}}'
        - name: AWS_SECRET_ACCESS_KEY
          value: '{{workflow.parameters.AWS_SECRET_ACCESS_KEY}}'
        - name: BUCKET
          value:  '{{workflow.parameters.BUCKET}}'
        - name: OBJECT
          value: '{{workflow.parameters.OBJECT}}'
        - name: CHECKSUM
          value: '{{workflow.parameters.CHECKSUM}}'
    outputs:
      parameters:
       - name: checksum_result
         valueFrom:
          path: /tmp/result
        
  # Kontainer som avviser et arkiv.
  # Her kan vi gjøre ting som å varsle arkivskaper om at jobben ikke avvist.
  - name: sjekksum-feil
    container:
      image: gcr.io/mottak/mailer
      imagePullPolicy: Always
      env:
        - name: MAILGUN_DOMAIN
          value: '{{workflow.parameters.MAILGUN_DOMAIN}}'
        - name: MAILGUN_API_KEY
          value: '{{workflow.parameters.MAILGUN_API_KEY}}'
        - name: NAME
          value: '{{workflow.parameters.NAME}}'
        - name: RECIPIENT
          value: '{{workflow.parameters.EMAIL}}'
        - name: SUBJECT
          value: 'Archieve rejected'
        - name: MESSAGE
          value: 'The archieve {{workflow.parameters.OBJECT}} was rejected due to checksum error. It will be deleted.'

  - name: avscan
    container: 
      image: gcr.io/mottak/s3-scan
      imagePullPolicy: Always
      env:
        - name: ENDPOINT
          value:  '{{workflow.parameters.ENDPOINT}}'
        - name: REGION_NAME
          value: 'us-east-1'
        - name: AWS_ACCESS_KEY_ID
          value: '{{workflow.parameters.AWS_ACCESS_KEY_ID}}'
        - name: AWS_SECRET_ACCESS_KEY
          value: '{{workflow.parameters.AWS_SECRET_ACCESS_KEY}}'
        - name: BUCKET
          value:  '{{workflow.parameters.BUCKET}}'
        - name: OBJECT
          value: '{{workflow.parameters.OBJECT}}'
        - name: CHECKSUM
          value: '{{workflow.parameters.CHECKSUM}}'
    outputs:
      parameters:
       - name: av_verdict
         valueFrom:
           path: /tmp/result
      artifacts:
        - name: avlog
          path: /tmp/av.log
          archive:
            none: {}


  - name: arkade5
    container:
      image: gcr.io/mottak/arkade5
      imagePullPolicy: Always
      env:
        - name: ENDPOINT
          value:  '{{workflow.parameters.ENDPOINT}}'
        - name: REGION_NAME
          value: 'us-east-1'
        - name: AWS_ACCESS_KEY_ID
          value: '{{workflow.parameters.AWS_ACCESS_KEY_ID}}'
        - name: AWS_SECRET_ACCESS_KEY
          value: '{{workflow.parameters.AWS_SECRET_ACCESS_KEY}}'
        - name: BUCKET
          value:  '{{workflow.parameters.BUCKET}}'
        - name: OBJECT
          value: '{{workflow.parameters.OBJECT}}'
        - name: CHECKSUM
          value: '{{workflow.parameters.CHECKSUM}}'
        - name: ARCHIEVE_TYPE
          value: '{{workflow.parameters.ARCHIEVE_TYPE}}'
    outputs:
      artifacts:
        - name: arkade-report
          path: /tmp/arkade.html
          archive:
            none: {}
    
  - name: nytt-arkiv
    container:
      image: gcr.io/mottak/mailer
      imagePullPolicy: Always
      env:
        - name: MAILGUN_DOMAIN
          value: '{{workflow.parameters.MAILGUN_DOMAIN}}'
        - name: MAILGUN_API_KEY
          value: '{{workflow.parameters.MAILGUN_API_KEY}}'
        - name: NAME
          value: 'Per Buer'
        - name: RECIPIENT
          value: 'perbue@arkivverket.no'
        - name: SUBJECT
          value: 'Archieve processed'
        - name: MESSAGE
          value: 'The archieve {{workflow.parameters.OBJECT}} has been processed. Check the object store.'
