#!/bin/bash

# Small bash script that makes a copy of and replaces the <LANGUAGE>_COMPONENT_NAME_TEMPLATE string in the <language>-workflow-template.yaml file.
# This is used for supporting similar Github Action workflows for multiple components in the mottak repo.

# Expects the component/service to be in its own folder in root of repo, mottak/<component-name>
# I.E: mottak/mottak-arkiv-service
PYTHON_COMPONENT_NAMES=("mottak-arkiv-service" "arkiv-downloader" "tusd" "kicker" "storage-sas-generator" "s3-scan-tar" "s3-unpack" "s3-checksum256" "mailer")
REACT_COMPONENT_NAMES=("mottak-arkiv-web")
BASH_COMPONENT_NAMES=("arkade5")

# Templates
COMPONENT_NAME_TEMPLATE='!COMPONENT_NAME!'
TOP_COMMENT_TEMPLATE='!TOP_COMMENT!'
TOP_COMMENT='THIS FILE IS AUTOGENERATED. EDIT TEMPLATES IN PARENT FOLDER'
PYTHON_TEMPLATE_FILE_NAME="python-workflow-template.yaml"
REACT_TEMPLATE_FILE_NAME="react-workflow-template.yaml"
BASH_TEMPLATE_FILE_NAME="bash-workflow-template.yaml"



for COMPONENT in "${PYTHON_COMPONENT_NAMES[@]}"
do
  OUTPUT_FILE='workflows/'"$COMPONENT"'-workflow.yaml'
  REPLACE_COMPONENT_NAME_CMD='s,'"$COMPONENT_NAME_TEMPLATE"','"$COMPONENT"',g'
  REPLACE_COMMENT_CMD='s,'"$TOP_COMMENT_TEMPLATE"','"$TOP_COMMENT"',g'

  echo "Adapting $PYTHON_TEMPLATE_FILE_NAME into $OUTPUT_FILE"
  sed -e "$REPLACE_COMPONENT_NAME_CMD" -e "$REPLACE_COMMENT_CMD" "$PYTHON_TEMPLATE_FILE_NAME" > "$OUTPUT_FILE"
done

for COMPONENT in "${REACT_COMPONENT_NAMES[@]}"
do
  OUTPUT_FILE='workflows/'"$COMPONENT"'-workflow.yaml'
  REPLACE_COMPONENT_NAME_CMD='s,'"$COMPONENT_NAME_TEMPLATE"','"$COMPONENT"',g'
  REPLACE_COMMENT_CMD='s,'"$TOP_COMMENT_TEMPLATE"','"$TOP_COMMENT"',g'

  echo "Adapting $REACT_TEMPLATE_FILE_NAME into $OUTPUT_FILE"
  sed -e "$REPLACE_COMPONENT_NAME_CMD" -e "$REPLACE_COMMENT_CMD" "$REACT_TEMPLATE_FILE_NAME" > "$OUTPUT_FILE"
done

for COMPONENT in "${BASH_COMPONENT_NAMES[@]}"
do
  OUTPUT_FILE='workflows/'"$COMPONENT"'-workflow.yaml'
  REPLACE_COMPONENT_NAME_CMD='s,'"$COMPONENT_NAME_TEMPLATE"','"$COMPONENT"',g'
  REPLACE_COMMENT_CMD='s,'"$TOP_COMMENT_TEMPLATE"','"$TOP_COMMENT"',g'

  echo "Adapting $BASH_TEMPLATE_FILE_NAME into $OUTPUT_FILE"
  sed -e "$REPLACE_COMPONENT_NAME_CMD" -e "$REPLACE_COMMENT_CMD" "$BASH_TEMPLATE_FILE_NAME" > "$OUTPUT_FILE"
done
