version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/mottak-arkiv-service"
    schedule:
      interval: "daily"
  - package-ecosystem: "poetry"
    directory: "/mottak-arkiv-service"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/mottak-arkiv-web"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/mottak-arkiv-web"
    schedule:
      interval: "daily"
