---
# Note that tasks have names defined here:
#   https://github.com/Microsoft/vsts-tasks/tree/master/Tasks
# So e.g. PublishTestResultsV2 becomes PublishTestResults@2
#
# The list of predefined build variables is found here:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=vsts
#
# The variable names are slightly different when using steps written in bash:
# All uppercase and '_' instead of '.'
# They can also be accessed as e.g. $(Agent.Id) from bash code in this file

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  DOCKER_BUILDKIT: 1
  dockerRegistryServiceConnection: 'arkivverket'
  clusterName: 'arkivverket-prod'
  namespace: 'mottak'

stages:
  - stage: BuildContainers
    displayName: Create and push all container images
    jobs:
      - job: BuildArkade
        displayName: Build and Publish Arkade
        steps:
          - task: Docker@2
            displayName: Build Arkade
            inputs:
              containerRegistry: arkivverket
              repository: mottak/arkade5
              command: buildAndPush
              Dockerfile: arkade5/Dockerfile

      - job: BuildInvitation
        displayName: Build and Publish Invitation
        steps:
          - task: Docker@2
            displayName: Build Invitation
            inputs:
              containerRegistry: arkivverket
              repository: mottak/invitation
              command: buildAndPush
              Dockerfile: invitation/Dockerfile

      - job: BuildLogService
        displayName: Build and Publish Log Service
        steps:
          - task: Docker@2
            displayName: Build Log Service
            inputs:
              containerRegistry: arkivverket
              repository: mottak/log
              command: buildAndPush
              Dockerfile: log/Dockerfile

      - job: BuildMailer
        displayName: Build and Publish Mailer
        steps:
          - task: Docker@2
            displayName: Build Mailer
            inputs:
              containerRegistry: arkivverket
              repository: mottak/mailer
              command: buildAndPush
              Dockerfile: mailer/Dockerfile

      - job: BuildChecksumService
        displayName: Build and Publish Checksum Service
        steps:
          - task: Docker@2
            displayName: Build Checksum Service
            inputs:
              containerRegistry: arkivverket
              repository: mottak/s3-checksum256
              command: buildAndPush
              Dockerfile: s3-checksum256/Dockerfile

      - job: BuildDeleteService
        displayName: Build and Publish Delete Service
        steps:
          - task: Docker@2
            displayName: Build delete service
            inputs:
              containerRegistry: arkivverket
              repository: mottak/s3-delete
              command: buildAndPush
              Dockerfile: s3-delete/Dockerfile

      - job: BuildAVScanner
        displayName: Build and Publish AV Scanner
        steps:
          - task: Docker@2
            displayName: Build AV scanner
            inputs:
              containerRegistry: arkivverket
              repository: mottak/s3-scan-tar
              command: buildAndPush
              Dockerfile: s3-scan-tar/Dockerfile

      - job: BuildTusd
        displayName: Build and Publish Tusd
        steps:
          - task: Docker@2
            displayName: Build tusd container
            inputs:
              containerRegistry: arkivverket
              repository: mottak/tusd
              command: buildAndPush
              Dockerfile: tusd/Dockerfile

  - stage: Deploy
    displayName: Deploy Stage
    dependsOn: BuildContainers
    jobs:
      - deployment: Deploy
        environment: $(clusterName)
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Deploy stage here
