# Note that tasks have names defined here:
#   https://github.com/Microsoft/vsts-tasks/tree/master/Tasks
# So e.g. PublishTestResultsV2 becomes PublishTestResults@2
#
# The list of predefined build variables is found here:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=vsts
#
# The variable names are slightly different when using steps written in bash: All uppercase and '_' instead of '.'
# They can also be accessed as e.g. $(Agent.Id) from bash code in this file

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
    DOCKER_BUILDKIT: 1

steps:
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: arkivverket

  - task: Docker@2
    displayName: Build Arkade
    inputs:
      containerRegistry: arkivverket
      repository: mottak/arkade5
      command: buildAndPush
      Dockerfile: arkade5/Dockerfile

  - task: Docker@2
    displayName: Build invitation
    inputs:
      containerRegistry: arkivverket
      repository: mottak/invitation
      command: buildAndPush
      Dockerfile: invitation/Dockerfile

  - task: Docker@2
    displayName: Build log service
    inputs:
      containerRegistry: arkivverket
      repository: mottak/log
      command: buildAndPush
      Dockerfile: log/Dockerfile

