# Note that tasks have names defined here:
#   https://github.com/Microsoft/vsts-tasks/tree/master/Tasks
# So e.g. PublishTestResultsV2 becomes PublishTestResults@2
#
# The list of predefined build variables is found here:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=vsts
#
# The variable names are slightly different when using steps written in bash: All uppercase and '_' instead of '.'
# They can also be accessed as e.g. $(Agent.Id) from bash code in this file

trigger:
  branches:
    include:
    - '*'
    - 'refs/tags/*'
  paths:
    exclude:
    - README.md
    - LICENSE
    - .gitignore

pool:
  vmImage: "ubuntu-latest"

variables:
    DOCKER_BUILDKIT: 1

steps:
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: arkivverket

  - task: Docker@2
    displayName: Build Arkade
    inputs:
      containerRegistry: arkivverket
      repository: mottak/arkade5
      command: build
      Dockerfile: arkade5/Dockerfile
      tags: |
        latest
        $(Build.SourceBranchName)
  - task: Docker@2
    displayName: Push Arkade
    inputs:
      containerRegistry: arkivverket
      repository: mottak/arkade5
      command: push
      Dockerfile: arkade5/Dockerfile
    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')
    
  - task: Docker@2
    displayName: Build invitation
    inputs:
      containerRegistry: arkivverket
      repository: mottak/invitation
      command: build
      Dockerfile: invitation/Dockerfile
      tags: |
        latest
        $(Build.SourceBranchName)
  - task: Docker@2
    displayName: Push invitation
    inputs:
      containerRegistry: arkivverket
      repository: mottak/invitation
      command: push
      Dockerfile: invitation/Dockerfile
    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')

  - task: Docker@2
    displayName: Build log service
    inputs:
      containerRegistry: arkivverket
      repository: mottak/log
      command: build
      Dockerfile: log/Dockerfile
      tags: |
        latest
        $(Build.SourceBranchName)
  - task: Docker@2
    displayName: Push log service
    inputs:
      containerRegistry: arkivverket
      repository: mottak/log
      command: push
      Dockerfile: log/Dockerfile
    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')

  - task: Docker@2
    displayName: Build mailer
    inputs:
      containerRegistry: arkivverket
      repository: mottak/mailer
      command: build
      Dockerfile: mailer/Dockerfile
      tags: |
        latest
        $(Build.SourceBranchName)
  - task: Docker@2
    displayName: Push mailer
    inputs:
      containerRegistry: arkivverket
      repository: mottak/mailer
      command: push
      Dockerfile: mailer/Dockerfile
    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')

  - task: Docker@2
    displayName: Build checksum service
    inputs:
      containerRegistry: arkivverket
      repository: mottak/s3-checksum256
      command: build
      Dockerfile: s3-checksum256/Dockerfile
      tags: |
        latest
        $(Build.SourceBranchName)
  - task: Docker@2
    displayName: Push checksum service
    inputs:
      containerRegistry: arkivverket
      repository: mottak/s3-checksum256
      command: push
      Dockerfile: s3-checksum256/Dockerfile
    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')

  - task: Docker@2
    displayName: Build delete service
    inputs:
      containerRegistry: arkivverket
      repository: mottak/s3-delete
      command: build
      Dockerfile: s3-delete/Dockerfile
      tags: |
        latest
        $(Build.SourceBranchName)
  - task: Docker@2
    displayName: Push delete service
    inputs:
      containerRegistry: arkivverket
      repository: mottak/s3-delete
      command: push
      Dockerfile: s3-delete/Dockerfile
    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')

  - task: Docker@2
    displayName: Build AV scanner
    inputs:
      containerRegistry: arkivverket
      repository: mottak/s3-scan-tar
      command: build
      Dockerfile: s3-scan-tar/Dockerfile
      tags: |
        latest
        $(Build.SourceBranchName)
  - task: Docker@2
    displayName: Push AV scanner
    inputs:
      containerRegistry: arkivverket
      repository: mottak/s3-scan-tar
      command: build
      Dockerfile: s3-scan-tar/Dockerfile
    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')

  - task: Docker@2
    displayName: Build tusd container
    inputs:
      containerRegistry: arkivverket
      repository: mottak/tusd
      command: build
      Dockerfile: tusd/Dockerfile
      tags: |
        latest
        $(Build.SourceBranchName)
  - task: Docker@2
    displayName: Push tusd container
    inputs:
      containerRegistry: arkivverket
      repository: mottak/tusd
      command: build
      Dockerfile: tusd/Dockerfile
    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')

