steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "--tag=gcr.io/$PROJECT_ID/s3-checksum256", "s3-checksum256"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "--tag=gcr.io/$PROJECT_ID/s3-scan", "s3-scan"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "--tag=gcr.io/$PROJECT_ID/arkade5", "arkade5"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "--tag=gcr.io/$PROJECT_ID/tusd", "tusd"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "--tag=gcr.io/$PROJECT_ID/invitation", "invitation"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "--tag=gcr.io/$PROJECT_ID/mailer", "mailer"]
    - name: "gcr.io/cloud-builders/docker"
    args: ["build", "--tag=gcr.io/$PROJECT_ID/s3-delete", "s3-delete"]
    - name: "gcr.io/cloud-builders/docker"
    args: ["build", "--tag=gcr.io/$PROJECT_ID/s3-rename", "s3-rename"]
images:
  [
    "gcr.io/$PROJECT_ID/s3-checksum256",
    "gcr.io/$PROJECT_ID/s3-scan",
    "gcr.io/$PROJECT_ID/arkade5",
    "gcr.io/$PROJECT_ID/tusd",
    "gcr.io/$PROJECT_ID/invitation",
    "gcr.io/$PROJECT_ID/mailer",
    "gcr.io/$PROJECT_ID/s3-delete",
    "gcr.io/$PROJECT_ID/s3-rename"
  ]
