apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mottak-ingress
  namespace: argo
  annotations:
    kubernetes.io/ingress.global-static-ip-name: mottak-ingress
spec:
  tls:
    - hosts:
      - mottak.arkivverket.dev
      - invitation.mottak.arkivverket.dev
      - tusd.mottak.arkivverket.dev
      - dashboard.mottak.arkivverket.dev
      secretName: tls-mottak-ingress      
  rules:
  - host: invitation.mottak.arkivverket.dev
    http:
      paths:  
      - backend:
          serviceName: invitation-service
          servicePort: 80
  - host: tusd.mottak.arkivverket.dev
    http:
      paths:
        - backend:
            serviceName: tusd-service
            servicePort: 80
