apiVersion: apps/v1
kind: Deployment
metadata:
  name: invitation-deployment
  labels:
    app: invitation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: invitation-app
  template:
    metadata:
      labels:
        run: invitation-app
    spec:
      containers:
      - image: arkivverket/invitation
        name: invitation-container
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
          # We need to find a way to register the service
          # that provides the URL to tusd so we can
          # pick it here so the inviter can encode this in the URL
          # Override this:
          - name:   UPLOAD_URL
            value: OVERRIDE_IN_PATCH
          - name: APPLICATION_SECRET
            valueFrom:
              secretKeyRef:
                name: invitation
                key: applicationSecret
          - name: DBSTRING
            valueFrom: 
              secretKeyRef:
                name: dsn
                key: dsn
          - name: MAILGUN_API_KEY
            valueFrom:
              secretKeyRef:
                name: mailgun
                key: apiKey
          - name: MAILGUN_DOMAIN
            valueFrom:
              secretKeyRef:
                name: mailgun
                key: emailDomain
