apiVersion: v1
kind: Service
metadata:
  name:  invitation-service

  # For external-dns, connects a service to DNS
  annotations:
    external-dns.alpha.kubernetes.io/hostname: OVERRIDE_IN_PATCH
    external-dns.alpha.kubernetes.io/ttl: "60"      #optional
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    run:  invitation-app    # references the deployment
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
