# Explicitly set none for repositry trigger
trigger:
  - none

resources:
  containers:
    - container: av-mottak/kriwal-test
      type: ACR
      azureSubscription: kriwal-test1
      resourceGroup: meta
      registry: arkivverket
      repository: av-mottak/kriwal-test
      trigger: true

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Kubernetes@1
  displayName: Deploy container to aks
  inputs:
    azureSubscriptionEndpoint: kriwal-test1
    azureResourceGroup: 'av-plattform-dev-aks-rg'
    kubernetesCluster: 'av-plattform-dev-aks'
    arguments: '-f $(Pipeline.Workspace)/azure-pipelines-releases/kicker-deployment.yaml'
    command: 'apply'
