apiVersion: v1
data:
  config: |
    artifactRepository:
      s3:
        # Override this:
        bucket:    pilot-spool
        keyPrefix: log
        # Override this too - if deployed outside Google
        endpoint: storage.googleapis.com
        accessKeySecret:
          name: s3-cred
          key: accessKeySecret
        secretKeySecret:
          name: s3-cred
          key: secretKeySecret
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"name":"workflow-controller-configmap","namespace":"argo"}}
  name: workflow-controller-configmap
  namespace: argo
  selfLink: /api/v1/namespaces/argo/configmaps/workflow-controller-configmap
