apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: invitation
  namespace: argo

spec:
  replicas: 2
  selector:
    matchLabels:
      run: invitation

  template:
    metadata:
      labels:
        run: invitation
    spec:
      containers:
      - image: gcr.io/mottak/invitation
        imagePullPolicy: Always
        name: invitation
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
          - name: UPLOAD_URL
            value: "http://35.228.155.81/files"
          - name: APPLICATION_SECRET
            valueFrom:
              secretKeyRef:
                name: invitation
                key: applicationSecret
          - name: DBSTRING
            valueFrom: 
              secretKeyRef:
                name: dsn
                key: dsn
          - name: MAILGUN_API_KEY
            valueFrom:
              secretKeyRef:
                name: mailgun
                key: apiKey
          - name: MAILGUN_DOMAIN
            valueFrom:
              secretKeyRef:
                name: mailgun
                key: emailDomain
