apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - invitation/invitation-deployment.yaml 
  - invitation/invitation-service.yaml
  - tusd/tusd-deployment.yaml
  - tusd/tusd-service.yaml
  - argo/argo-artifacts.yaml

namespace: argo

patches:
  - patches.yaml
  - patch-artifacts.yaml

#patchesJson6902:
#- target:
#    group: apps
#    version: v1
#    kind: Deployment
#    name: invitation
#    namespace: argo
#  path: patch-invitation.yaml
