# Docs for patching: 
# https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md

apiVersion: apps/v1
kind: Deployment
metadata:
  name: invitation
  namespace: argo
spec:
  replicas: 3
  template:
    spec:
      containers:
        env:
          - name:   UPLOAD_URL
            value: "http://invitation.gke.digitalarkiv.net/files"
