# In this file you override your local settings.
# This file should not be tracked in the main git repo, but rather in your settings somehow
# Go over this file and replace all the XXX with your local values.
# https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md

apiVersion: apps/v1
kind: Deployment
metadata:
  name: invitation-deployment

spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: invitation-container
          env:
            - name: UPLOAD_URL
              value: XXX


--- 
apiVersion: v1
kind: Service
metadata:
  name:  invitation-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: XXX

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tusd-deployment

spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: tusd-container
          env: 
          - name: ENDPOINT
            value: XXX
          - name: AWS_REGION
            value: XXX
          - name: BUCKET
            value: XXX
--- 
apiVersion: v1
kind: Service
metadata:
  name:  tusd-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: XXX
---
# Todo: Kustomize the Argo configmap with configmapgenerator
