apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tusd
  namespace: argo

spec:
  replicas: 2
  selector:
    matchLabels:
      run: tusd
  template:
    metadata:
      labels:
        run: tusd
    spec:
      containers:
      - image: gcr.io/mottak/tusd
        imagePullPolicy: Always
        name: tusd
        ports:
        - containerPort: 1080
          protocol: TCP
        # GCS auth happends through a magic JSON file.
        livenessProbe:
          httpGet:
            path: /
            port: 1080
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
          - name: gcs
            mountPath: "/etc/gcs"
            readOnly: true
        env:
            # Override this if outside google:
            # If on AWS, this should be unset, methinks.
          - name: ENDPOINT
            value: https://storage.googleapis.com
            # Override this?
          - name: AWS_REGION
            value: us-east-1
            # Override this if you're not Per.
          - name: BUCKET
            value: pilot-spool
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-cred
                key: accessKeySecret
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-cred
                key: secretKeySecret
          - name: DBSTRING
            valueFrom: 
              secretKeyRef:
                name: dsn
                key: dsn
      volumes:
       - name: gcs
         secret:
           secretName: gcs-cred
