apiVersion: v1
kind: Service
metadata:
  namespace: argo
  name:  tusd-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 1080 
  selector:
    run:  tusd
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
