apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tusd
  namespace: argo

spec:
  selector:
    matchLabels:
      run: tusd
  template:
    metadata:
      labels:
        run: tusd
    spec:
      containers:
      - image: gcr.io/mottak/tusd
        imagePullPolicy: Always
        name: tusd
        ports:
        - containerPort: 1080
          protocol: TCP
        # GCS auth happends through a magic JSON file.
        volumeMounts:
          - name: gcs
            mountPath: "/etc/gcs"
            readOnly: true
        env:
          - name: DBSTRING
            valueFrom: 
              secretKeyRef:
                name: dsn
                key: dsn
      volumes:
       - name: gcs
         secret:
           secretName: gcs-cred
