# This is SecretProviderClass example using service-principal for authentication with Key Vault
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}-csidriver-keyvault
  namespace: {{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}
  labels:
    aadpodidbinding: {{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}-id-keyvault
spec:
  provider: azure
  secretObjects:                              # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - data:
    - key: {{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}-secret-dsn                      # data field to populate
      objectName: {{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}-dsn                        # name of the mounted content to sync. this could be the object name or the object alias
    secretName: {{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}-dsn                     # name of the Kubernetes Secret object
    type: Opaque                              # type of the Kubernetes Secret object e.g. Opaque, kubernetes.io/tls
  - data:
    - key: mailgun-secret
      objectName: mailgun-secret                        # name of the mounted content to sync. this could be the object name or the object alias
    secretName: mailgun-secret                     # name of the Kubernetes Secret object
    type: Opaque                              # type of the Kubernetes Secret object e.g. Opaque, kubernetes.io/tls
  - data:
    - key: {{ required "Missing value AV_MOTTAK_TUSD_KICKER_SB_ENDPOINT" .Values.AV_MOTTAK_TUSD_KICKER_SB_ENDPOINT }}
      objectName: {{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}-sb-endpoint-argo-kicker                        # name of the mounted content to sync. this could be the object name or the object alias
    secretName: {{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}-sb-endpoint-argo-kicker                     # name of the Kubernetes Secret object
    type: Opaque
  - data:
    - key: storageaccount-key
      objectName: storageaccount-key                        # name of the mounted content to sync. this could be the object name or the object alias
    secretName: storageaccount-key                     # name of the Kubernetes Secret object
    type: Opaque                              # type of the Kubernetes Secret object e.g. Opaque, kubernetes.io/tls
  parameters:
    usePodIdentity: "true"         # [OPTIONAL] if not provided, will default to "false"
    keyvaultName: "{{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}-vault"          # the name of the KeyVault
    cloudName: ""          # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: {{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}-dsn
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: {{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}-sb-endpoint-argo-kicker
          objectType: secret
          objectVersion: ""
        - |
          objectName: storageaccount-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: mailgun-secret
          objectType: secret
          objectVersion: ""
    resourceGroup: "{{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}-rg"
    tenantId: "{{ required "Missing value TENANT_ID_KEYVAULT" .Values.TENANT_ID_KEYVAULT }}"                    # the tenant ID of the KeyVault
