apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}-nginx-mount-secret
  namespace: {{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}
  labels:
    aadpodidbinding: "{{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}-id-keyvault"
spec:
  selector:
    matchLabels:
      app: {{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}-nginx-mount-secret
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}-nginx-mount-secret
        aadpodidbinding: "{{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}-id-keyvault"
    spec:
      containers:
        - name: nginx
          imagePullPolicy: Always
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/mnt/secrets-store"
              name: secrets-store-inline
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "{{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}-csidriver-keyvault"

