kind: Pod
apiVersion: v1
metadata:
  name: {{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}-csi-attachment-mount-secrets
  namespace: {{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}
  labels:
    aadpodidbinding: "{{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}-id-keyvault"
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "{{ required "Missing value NAMESPACE" .Values.AV_NAMESPACE }}-csidriver-keyvault"
