import pytest

from app.services.domain.metadatafil import content_type2metadata_type, MetadataType, Metadatafil


def test_content_type2metadata_type__success():
    """
    GIVEN   the string 'text/xml' as content_type
    WHEN    calling the method content_type2metadata_type
    THEN    check that return value is MetadataType.XML_METS
    """
    expected = MetadataType.XML_METS
    actual = content_type2metadata_type('text/xml')
    assert actual == expected


def test_content_type2metadata_type__failure():
    """
    GIVEN   the string 'text' as content_type
    WHEN    calling the method content_type2metadata_type
    THEN    check that a ValueError Exception has been raised
    """
    with pytest.raises(ValueError):
        content_type2metadata_type('text')


def test_metadatafil__success():
    """
    GIVEN   the strings filnavn, content_type and innhold
    WHEN    creating an instance of class Metadatafil
    THEN    check that values that should be generated by the database is allowed to be None
    """
    expected_dict = {
        'id': None,
        'arkivuttrekk_id': None,
        'filnavn': 'filnavn_test',
        'type': MetadataType.XML_METS,
        'innhold': 'innhold_test',
        'opprettet': None
    }
    actual = Metadatafil("filnavn_test", "text/xml", "innhold_test")
    assert vars(actual) == expected_dict

