# Explicitly set none for repository trigger
trigger: none

resources:          # types: pipelines | repositories | containers | builds | packages
  containers:
    - container: cont # identifier for the container resource
      type: ACR # type of the registry like ACR, GCR etc.
      azureSubscription: arkivverket-meta-connection # Azure subscription (ARM service connection) for container registry;
      resourceGroup: meta # resource group for your ACR
      registry: arkivverket # registry for container images
      repository: "av-mottak/kicker" # name of the container image repository in ACR
      trigger:
        tags:
          include:
          - "*"

variables:
  env: dev
  jobName: deploy_kicker
  displayName: Deploy kicker
  valuesContainerKey: AV_MOTTAK_KICKER_TAG  # As found in values/<env>/values-containers.yaml
  deploymentYamlName: kicker-deployment.yaml # As found in k8s/templates/<app>-deployment.yaml


pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: ${{ variables.jobName }}
    displayName: ${{ variables.displayName }}
    steps:
      # To allow for using git commands later in the pipeline
      - checkout: self
        persistCredentials: true

      - template: deploy.yaml
        parameters:
          env: $(env)
          valuesContainerKey: $(valuesContainerKey)
          containerTag: ${{ resources.container.cont.tag }}
          deploymentYamlName: $(deploymentYamlName)
