# Explicitly set none for repository trigger
trigger: none

resources:          # types: pipelines | repositories | containers | builds | packages
  containers:
    - container: mycontainer # identifier for the container resource
      type: ACR # type of the registry like ACR, GCR etc.
      azureSubscription: arkivverket-meta-connection # Azure subscription (ARM service connection) for container registry;
      resourceGroup: meta # resource group for your ACR
      registry: arkivverket # registry for container images
      repository: "da-mottak/mottak-arkiv-service" # name of the container image repository in ACR
      trigger:
        tags:
          include:
            - "*"

variables:
  env: dev
  jobName: deploy_mottak_arkiv_service
  displayName: Deploy mottak-arkiv-service
  valuesContainerKey: DA_MOTTAK_ARKIV_SERVICE_TAG  # As found in values/<env>/values-containers.yaml
  deploymentYamlName: mottak-arkiv-service-deployment.yaml # As found in k8s/templates/<app>-deployment.yaml


pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: ${{ variables.jobName }}
    displayName: ${{ variables.displayName }}
    steps:
      # To allow for using git commands later in the pipeline
      - checkout: self
        persistCredentials: true

      - template: deploy.yaml
        parameters:
          env: $(env)
          valuesContainerKey: $(valuesContainerKey)
          containerTag: $(resources.container.mycontainer.tag)
          deploymentYamlName: $(deploymentYamlName)
