apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tusd.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      run: tusd
  template:
    metadata:
      labels:
        run: tusd
    spec:
      volumes:
        - name: gcs
          secret:
            secretName: gcs-cred

      containers:
      - image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: tusd-container
        ports:
        - containerPort: 1080
          protocol: TCP
        # GCS auth happends through a magic JSON file.
        livenessProbe:
          httpGet:
            path: /
            port: 1080
          initialDelaySeconds: 10
          periodSeconds: 10
        # If using GCS as a backend we must use the native interface
        # because of compat issues tusd <--> gcs
        volumeMounts:
          - name: gcs
            mountPath: "/etc/gcs"
            readOnly: true
        env:
            # Override this if outside google:
            # If on AWS, this should be unset, methinks.
          - name: DBSTRING
            value: mottak-tusd-dbstring-inject@azurekeyvault
          - name: MAILGUN_API_KEY
            value: mottak-tusd-mailgun-api-key-inject@azurekeyvault
          - name: MAILGUN_DOMAIN
            value: {{ required "tusd: set a mailgun_domain during deployment" .Values.mailgun_domain | quote }}
