apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  config: |
    artifactRepository:
      archiveLogs: false
      s3:
        # Override this:
        bucket:    artifacts
        # Override this too - if deployed outside Google
        endpoint: http://minio-service.argo.svc.cluster.local:9000
        insecure: true
        accessKeySecret:
          name: minio-cred
          key: accessKeySecret
        secretKeySecret:
          name: minio-cred
          key: secretKeySecret
