apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  config: |
    artifactRepository:
      archiveLogs: true
      s3:
        # Override this:
        bucket:    mottak
        keyPrefix: log
        # Override this too - if deployed outside Google
        endpoint: https://storage.googleapis.com
        accessKeySecret:
          name: s3-cred
          key: accessKeySecret
        secretKeySecret:
          name: s3-cred
          key: secretKeySecret
