apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "invitation.fullname" . }}
  labels:
    app: invitation-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      run: invitation-app
  template:
    metadata:
      labels:
        run: invitation-app
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        name: {{ .Chart.Name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
          # We need to find a way to register the service
          # that provides the URL to tusd so we can
          # pick it here so the inviter can encode this in the URL
          # Override this:
          - name:   UPLOAD_URL
            value: {{ required "invitation: set upload_url during deployment" .Values.upload_url | quote }}
          - name: APPLICATION_SECRET # XSS protection
            value: mottak-invitation-application-secret-inject@azurekeyvault
          - name: DBSTRING
            value: mottak-invitation-dbstring-inject@azurekeyvault
          - name: MAILGUN_API_KEY
            value: mottak-invitation-mailgun-api-key-inject@azurekeyvault
          - name: MAILGUN_DOMAIN
            value: {{ required "invitation: set a mailgun_domain during deployment" .Values.mailgun_domain | quote }}
