apiVersion: v1
kind: Service
metadata:
  name:  invitation-service
spec:
  selector:
    app:  invitation-app    # references the deployment
  ports:
    - name: http
      port: 80
      targetPort: 80
