apiVersion: v1
kind: Service
metadata:
  name:  tusd-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: OVERRIDE_IN_PATCH
    external-dns.alpha.kubernetes.io/ttl: "60" #optional
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 1080 
  selector:
    run:  tusd
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
