on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Copy values-container.yaml to [test prod]'
        required: true


jobs:
  copyFiles:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          repository: arkivverket/mottak-k8s-config
          ref: master
          ssh-key: ${{ secrets.MOTTAK_K8S_CONFIG_SECRET }}
