on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Copy values-container.yaml to [test prod]'
        required: true


jobs:
  copyFiles:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "env: ${{ github.event.inputs.env }}"

      - uses: actions/checkout@v2
        with:
          repository: arkivverket/mottak-k8s-config
          ref: master
          ssh-key: ${{ secrets.MOTTAK_K8S_CONFIG_SECRET }}

      - run: |
          if [ ${{ github.event.inputs.env }} == "test" ]; then
            echo "Copying dev to test"
            mkdir -p values/test && cp values/dev/values-containers.yaml values/dev/values-containers.yaml
          elif [ ${{ github.event.inputs.env }} == "prod"]; then
            echo "Copying dev to test"
            mkdir -p values/prod && cp values/dev/values-containers.yaml values/dev/values-containers.yaml
          else
            echo "${{ github.event.inputs.env }} is not supported as an environment"
          fi

      - run: |
          git config user.name mottak-github-actions
          git config user.email mottak-github-actions@github.com
          git add .
          git commit -m "Copied container values to ${{ github.event.inputs.env }}"
#          git push
