---
parameters:
  - name: appName
    type: string

  - name: containerRepo
    type: string

  - name: containerRegServiceConn
    type: string

steps:

  # Get the version number from the tag
  - bash: |
      VERSION_FROMTAG=$(echo $BUILD_SOURCEBRANCHNAME | sed -E 's/^v([0-9]+(\.[0-9]+)*)$/\1/')
      echo "##vso[task.setvariable variable=VersionFromTag]$VERSION_FROMTAG"

  # Create docker image and Push it to the container registry
  - task: Docker@2
    displayName: Build and push ${{ parameters.appName }}
    inputs:
      containerRegistry: ${{ parameters.containerRegServiceConn }}
      repository: ${{ parameters.containerRepo }}/${{ parameters.appName }}
      command: buildAndPush
      Dockerfile: ${{ parameters.appName }}/Dockerfile
      tags: |
        latest
        $(VersionFromTag)
