# Explicitly set none for repository trigger
trigger: none

resources:          # types: pipelines | repositories | containers | builds | packages
  containers:
    - container: kicker # identifier for the container resource
      type: ACR # type of the registry like ACR, GCR etc.
      azureSubscription: arkivverket-meta-connection # Azure subscription (ARM service connection) for container registry;
      resourceGroup: meta # resource group for your ACR
      registry: arkivverket # registry for container images
      repository: "av-mottak/kicker" # name of the container image repository in ACR
      trigger:
        tags:
          include:
          - "*"


pool:
  vmImage: 'ubuntu-latest'

variables:
  env: dev


stages:
  - stage: Deploy
    displayName: Deploy kicker
    jobs:
      - job: Deploy kicker
        displayName: Deploy kicker
        steps:
          - template: deploy.yaml
            parameters:
              env: $(env)
              valuesContainerKey: AV_MOTTAK_KICKER_TAG # As found in values-containers.yaml
              containerTag: $(resources.container.kicker.tag)
              deploymentYamlName: kicker-deployment.yaml
