# Explicitly set none for repository trigger
trigger: none

resources:          # types: pipelines | repositories | containers | builds | packages
  containers:
    - container: kicker # identifier for the container resource
      type: ACR # type of the registry like ACR, GCR etc.
      azureSubscription: arkivverket-meta-connection # Azure subscription (ARM service connection) for container registry;
      resourceGroup: meta # resource group for your ACR
      registry: arkivverket # registry for container images
      repository: "av-mottak/kicker" # name of the container image repository in ACR
      trigger:
        tags:
          include:
          - "*"


pool:
  vmImage: 'ubuntu-latest'


steps:
  - script: |
      echo Hello world
      echo $(resources.container.kicker.tag)
      echo $(resources.container.kicker.type)
      echo $(resources.container.kicker.registry)
      echo $(resources.container.kicker.repository)
      echo $(resources.container.kicker.digest)
      echo $(resources.container.kicker.URI)
      echo $(resources.container.kicker.location)
    displayName: 'Command Line Script'

  - script: |
      cd azure-pipelines
      ls
      ENV='dev'
      OUTPUT_FOLDER="k8s/output/$ENV"
      helm template --values "values-$ENV.yaml" --set AV_MOTTAK_KICKER_CONTAINER=$(resources.container.kicker.repository):$(resources.container.kicker.tag) --output-dir "$OUTPUT_FOLDER" k8s/
    displayName: 'Running helm template'

  - task: KubernetesManifest@0
    inputs:
      action: 'deploy'
      kubernetesServiceConnection: 'kriwal-test'
      namespace: 'av-mottak-dev'
      manifests: 'azure-pipelines/k8s/output/dev/av-mottak/templates/kicker-deployment.yaml'
