# Explicitly set none for repositry trigger
resources:          # types: pipelines | repositories | containers | builds | packages
  containers:
    - container: kriwalTest # identifier for the container resource
      type: ACR # type of the registry like ACR, GCR etc.
      azureSubscription: kriwal-test1 # Azure subscription (ARM service connection) for container registry;
      resourceGroup: meta # resource group for your ACR
      registry: arkivverket # registry for container images
      repository: "av-mottak/kriwal-test" # name of the container image repository in ACR
      trigger:
        tags:
          include: []
          exclude: []


pool:
  vmImage: 'ubuntu-latest'


steps:
  - script: |
      echo Hello world
      echo $(resources.container.kriwalTest.tag)
    displayName: 'Command Line Script'
