# Explicitly set none for repository trigger
trigger: none

resources:          # types: pipelines | repositories | containers | builds | packages
  containers:
    - container: kicker # identifier for the container resource
      type: ACR # type of the registry like ACR, GCR etc.
      azureSubscription: arkivverket-meta-connection # Azure subscription (ARM service connection) for container registry;
      resourceGroup: meta # resource group for your ACR
      registry: arkivverket # registry for container images
      repository: "av-mottak/kicker" # name of the container image repository in ACR
      trigger:
        tags:
          include:
          - "*"


pool:
  vmImage: 'ubuntu-latest'

variables:
  env: dev


steps:
  # Use Python version (defaults to 3.x) and appends to path
  - tasks: UsePythonVersion@0

  - script: |
      python -m pip install -U pip
      pip install poetry
      poetry install
    displayName: 'Install software'

  - script: |
      poetry run python update_values_yaml.py --file "values/$(env)/values-containers.yaml" --key AV_MOTTAK_KICKER_CONTAINER --value $(resources.container.kicker.tag)
    displayName: 'Update tag in values-container.yaml'

  - script: |
      OUTPUT_FOLDER="k8s/output/$(env)"
      helm template --values "values/$(env)/values.yaml" --values "values/$(env)/values-containers.yaml" --output-dir "$OUTPUT_FOLDER" k8s/
    displayName: 'Running helm template'

  - task: KubernetesManifest@0
    inputs:
      action: 'deploy'
      kubernetesServiceConnection: 'av-mottak-dev@av-plattform-dev-aks-connection'
      namespace: 'av-mottak-dev'
      manifests: 'azure-pipelines/k8s/output/dev/av-mottak/templates/kicker-deployment.yaml'
