---
# Note that tasks have names defined here:
#   https://github.com/Microsoft/vsts-tasks/tree/master/Tasks
# So e.g. PublishTestResultsV2 becomes PublishTestResults@2
#
# The list of predefined build variables is found here:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=vsts
#
# The variable names are slightly different when using steps written in bash:
# All uppercase and '_' instead of '.'
# They can also be accessed as e.g. $(Agent.Id) from bash code in this file

trigger:
  branches:
    include:
      - '*'
      - 'refs/tags/*'
  paths:
    exclude:
      - README.md
      - LICENSE
      - .gitignore

pool:
  vmImage: "ubuntu-latest"

variables:
  DOCKER_BUILDKIT: 1
  dockerRegistryServiceConnection: 'arkivverket'
  clusterName: 'arkivverket-prod'
  namespace: 'mottak'
  containerRepo: 'mottak'

stages:
  - stage: Build
    displayName: Build all container images
    jobs:
      - job: BuildArkade
        displayName: Build Arkade
        steps:
          - template: build.yaml
            parameters:
              appName: 'arkade5'
              containerRepo: 'mottak'
              containerRegServiceConn: ${{ variables.dockerRegistryServiceConnection }}

      - job: BuildInvitation
        displayName: Build Invitation
        steps:
          - template: build.yaml
            parameters:
              appName: 'invitation'
              containerRepo: 'mottak'
              containerRegServiceConn: ${{ variables.dockerRegistryServiceConnection }}

      - job: BuildMailer
        displayName: Build Mailer
        steps:
          - template: build.yaml
            parameters:
              appName: 'mailer'
              containerRepo: 'mottak'
              containerRegServiceConn: ${{ variables.dockerRegistryServiceConnection }}

      - job: BuildChecksumService
        displayName: Build Checksum Service
        steps:
          - template: build.yaml
            parameters:
              appName: 's3-checksum256'
              containerRepo: 'mottak'
              containerRegServiceConn: ${{ variables.dockerRegistryServiceConnection }}

      - job: BuildDeleteService
        displayName: Build Delete Service
        steps:
          - template: build.yaml
            parameters:
              appName: 's3-delete'
              containerRepo: 'mottak'
              containerRegServiceConn: ${{ variables.dockerRegistryServiceConnection }}

      # - job: BuildRenameService
      #   displayName: Build Rename Service
      #   steps:
      #     - template: build.yaml
      #       parameters:
      #         appName: 's3-rename'
      #         containerRepo: 'mottak'
      #         containerRegServiceConn: ${{ variables.dockerRegistryServiceConnection }}

      - job: BuildAVScanner
        displayName: Build AV Scanner
        steps:
          - template: build.yaml
            parameters:
              appName: 's3-scan-tar'
              containerRepo: 'mottak'
              containerRegServiceConn: ${{ variables.dockerRegistryServiceConnection }}

      - job: BuildTusd
        displayName: Build Tusd
        steps:
          - template: build.yaml
            parameters:
              appName: 'tusd'
              containerRepo: 'mottak'
              containerRegServiceConn: ${{ variables.dockerRegistryServiceConnection }}


  - stage: Package
    displayName: Package Mottak as Helm Chart
    dependsOn: Build
    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')
    jobs:
      - job:
        displayName: Package as Helm Chart
        steps:
          - template: package.yaml
            parameters:
              appName: 'mottak'
              helmPackageArtifactName: 'mottak-helm-package'


  - stage: Deploy
    displayName: Deploy Stage
    dependsOn: Package
    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')
    jobs:
      - deployment: DeployInvitation
        environment: $(clusterName)
        strategy:
          runOnce:
            deploy:
              steps:
                - template: deploy.yaml
                  parameters:
                    appName: 'mottak'
                    helmPackageArtifactName: 'mottak-helm-package'
                    helmReleaseName: 'mottak.mottak'
                    clusterName: ${{ variables.clusterName }}
                    namespace: ${{ variables.namespace }}
