# Explicitly set none for repositry trigger
resources:
  containers:
    - container: test
      type: ACR
      azureSubscription: kriwal-test1
      resourceGroup: meta
      registry: arkivverket
      repository: av-mottak/kriwal-test
      trigger: true

pool:
  vmImage: 'ubuntu-latest'


steps:
  - script: |
      echo Hello world

    displayName: 'Command Line Script'
