apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: verify-overforingspakke-
spec:
  entrypoint: verify-overforingspakke
  templates:
    - name: verify-overforingspakke
      dag:
        tasks:
          - name: task-checksum-check
            template: checksum-check
          - name: task-avscan
            template: avscan
            dependencies: [ task-checksum-check ]
          - name: task-notify-coordinator
            template: notify-coordinator
            dependencies: [ task-avscan ]
            arguments:
              parameters:
                - name: av_result
                  value: "{{tasks.task-avscan.outputs.parameters.av_result}}"
              artifacts:
                - name: av_log
                  from: "{{tasks.task-avscan.outputs.artifacts.av_log}}"

    - name: checksum-check
      container:
        image: arkivverket.azurecr.io/da-mottak/s3-checksum256:{{workflow.parameters.CHECKSUM_TAG}}
        imagePullPolicy: Always
        env:
          - name: TUSD_OBJECT_NAME
            value: "{{workflow.parameters.TUSD_OBJEKT_NAVN}}"
          - name: SJEKKSUM
            value: "{{workflow.parameters.SJEKKSUM}}"
          - name: OBJECTSTORE
            value: abs
          - name: BUCKET
            value: "tusd-storage"
          - name: AZURE_ACCOUNT
            valueFrom:
              secretKeyRef:
                name: storageaccount-name
                key: storageaccount-name
          - name: AZURE_KEY
            valueFrom:
              secretKeyRef:
                name: storageaccount-key
                key: storageaccount-key
      outputs:
        parameters:
          - name: checksum_result
            valueFrom:
              path: /tmp/result
        artifacts:
          - name: checksumlog
            path: "/tmp/checksum.log"
            archive:
              none: {}

    - name: avscan
      container:
        image: arkivverket.azurecr.io/da-mottak/s3-scan-tar:{{workflow.parameters.AVSCAN_TAG}}

        imagePullPolicy: Always
        env:
          - name: TUSD_OBJECT_NAME
            value: "{{workflow.parameters.TUSD_OBJEKT_NAVN}}"
          - name: OBJECTSTORE
            value: abs
          - name: BUCKET
            value: "tusd-storage"
          - name: AZURE_STORAGE_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: storageaccount-connection-string
                key: storageaccount-connection-string
          - name: OUTPUT_PATH_LOG
            value: /tmp/avlog
          - name: OUTPUT_PATH_RESULT
            value: /tmp/result
      outputs:
        parameters:
          - name: av_result
            valueFrom:
              path: /tmp/result
        artifacts:
          - name: av_log
            path: /tmp/avlog
            archive:
              none: {}  # no compression, default is tar+gzip compression

    - name: notify-coordinator
      inputs:
        parameters:
          - name: av_result
        artifacts:
          - name: av_log
            path: /tmp/attachments/av_log.txt
          - name: message
            path: /tmp/message
            raw:
              data: |
                Verifisering av overføringspakke utført.
                Gjelder overføringspakke:
                    - tittel: {{workflow.parameters.ARKIVUTTREKK_TITTEL}}
                    - arkivuttrekk objekt id: {{workflow.parameters.ARKIVUTTREKK_OBJ_ID}}
                    - invitasjons id: {{workflow.parameters.EKSTERN_ID}}

                {{inputs.parameters.av_result}}

                Vedlagt denne e-post er loggen fra antivirus-skanning.
                Vennligst se over
      container:
        image: arkivverket.azurecr.io/da-mottak/mailer:{{workflow.parameters.MAILER_TAG}}

        imagePullPolicy: Always
        env:
          - name: MAILGUN_DOMAIN
            value: mg.mottak.digitalarkivet.no
          - name: MAILGUN_API_KEY
            valueFrom:
              secretKeyRef:
                name: mailgun-secret
                key: mailgun-secret
          - name: NAME
            value: "Koordinator"  # {{workflow.parameters.KOORDINATOR_NAVN}}
          - name: RECIPIENT
            value: "{{workflow.parameters.KOORDINATOR_EPOST}}"
          - name: SUBJECT
            value: "Overføringspakke skannet: {{workflow.parameters.ARKIVUTTREKK_TITTEL}}"
          - name: MESSAGE
            value: /tmp/message
          - name: ATTACHMENTS
            value: /tmp/attachments
