# !TOP_COMMENT!
on:
  push:
    branches: [ develop ]
    paths:
      - '!COMPONENT_NAME!/**'
      - '.github/workflows/!COMPONENT_NAME!-workflow.yaml'
  pull_request:
    paths:
      - '!COMPONENT_NAME!/**'
      - '.github/workflows/!COMPONENT_NAME!-workflow.yaml'

jobs:
  test:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '!COMPONENT_NAME!'

    steps:
      - uses: actions/checkout@v2

      - name: Lint with shellcheck
        run: |
          shellcheck *.sh
      - name: Verify build docker image
        run: |
          docker build . -t !COMPONENT_NAME!:${{ github.sha }}

  build-and-push-docker-image:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '!COMPONENT_NAME!'
    needs: test
    if: github.ref == 'refs/heads/develop'

    steps:
      - uses: actions/checkout@v2

      - name: Build and push docker image
        uses: azure/docker-login@v1
        with:
          login-server: arkivverket.azurecr.io
          username: ${{ secrets.ARKIVVERKET_AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.ARKIVVERKET_AZURE_REGISTRY_PASSWORD }}

      - run: |
          docker build . -t arkivverket.azurecr.io/da-mottak/!COMPONENT_NAME!:${{ github.sha }}
          docker push arkivverket.azurecr.io/da-mottak/!COMPONENT_NAME!:${{ github.sha }}

  update-deployment-version:
    needs:
      - build-and-push-docker-image
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python and Poetry
        run: |
          python -m pip install -U pip
          pip install poetry

      - uses: actions/checkout@v2
        with:
          repository: arkivverket/mottak-k8s-config
          ref: master
          ssh-key: ${{ secrets.MOTTAK_K8S_CONFIG_SECRET }}

      - name: Install dependencies
        run: |
          poetry install

      - name: Update tag for !COMPONENT_NAME! in values-container.yaml
        run: |
          echo "Running: python update_values_yaml.py --file "values/dev/values-containers.yaml" --key !COMPONENT_CONTAINER_NAME_TAG_NAME! --value ${{ github.sha }}"
          poetry run python update_values_yaml.py --file "values/dev/values-containers.yaml" --key !COMPONENT_CONTAINER_NAME_TAG_NAME! --value ${{ github.sha }}

      - name: Running helm template
        run: |
          OUTPUT_FOLDER="k8s/output/dev"
          helm template --values "values/dev/values.yaml" --values "values/dev/values-containers.yaml" --output-dir "$OUTPUT_FOLDER" k8s/

      - name: Commit changes
        run: |
          git config --local user.name "GitHub workflow !COMPONENT_NAME!-deployment.yaml"
          git config --local user.email "github-actions[bot]"
          git add -A
          echo $(git status)
          git commit -m "Set !COMPONENT_NAME! image tag in dev to ${{ github.sha }}"
          git push origin master
